//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by qMView.rc
//
#define IDAPPLY                         3
#define IDD_ABOUTBOX                    100
#define CG_ID_VIEW_FRAMETREEDLG         104
#define CG_IDD_FRAMEMANAGER2            105
#define CG_ID_VIEW_FRAMEMANAGER2        106
#define IDD_PP_GENERAL                  107
#define CG_IDR_POPUP_NODE_TREE_CTRL     108
#define IDR_SKIN                        128
#define IDR_QMVIEWTYPE                  129
#define IDB_SPLASH                      130
#define IDB_LOGO                        131
#define IDB_RAVEN                       132
#define IDR_VIEWPOSBAR                  139
#define IDR_ANIMBAR                     145
#define IDR_ANIMBAR1                    146
#define IDB_BITMAP1                     147
#define IDC_HAND_OPEN                   151
#define IDC_HAND_CLOSED                 152
#define IDC_HAND_ROTATE                 153
#define CG_IDD_TREEMANAGER              155
#define IDB_BITMAP2                     157
#define IDB_BITMAP3                     158
#define IDB_BITMAP4                     159
#define IDD_NODE_PROP                   160
#define IDD_TICKER                      164
#define IDC_MAGNIFIER                   166
#define IDD_JOINT_ANGLES                168
#define IDD_JOINT_LOCK_ANGLES           169
#define IDR_SKIN_POPUP_MENU             176
#define IDR_QMVIEWTYPE1                 177
#define IDC_SKINTREE                    1000
#define IDC_FRAMETREE                   1001
#define IDC_NODETREE                    1005
#define IDC_JOINTTREE                   1006
#define IDC_TICKTOG                     1009
#define IDC_EDIT1                       1010
#define IDC_SPIN1                       1011
#define IDC_YVAL                        1014
#define IDC_ZVAL                        1015
#define IDC_XVAL                        1016
#define IDC_APPLY                       1017
#define IDC_XVAL2                       1018
#define IDC_PPGEN_FRAMES                1018
#define IDC_YVAL2                       1019
#define IDC_PPGEN_GLCOMMANDS            1019
#define IDC_ZVAL2                       1020
#define IDC_PPGEN_SKINS                 1020
#define IDC_PPGEN_TRIS                  1021
#define IDC_PPGEN_GROUPS                1022
#define IDC_PPGEN_SKINWIDTH             1023
#define IDC_PPGEN_SKINHEIGHT            1024
#define IDC_PPGEN_STVERTS               1025
#define IDC_PPGEN_VERTS                 1026
#define ID_PALETTE_IMPORT               32772
#define ID_PALETTE_EXPORT               32773
#define ID_SKIN_IMPORT                  32774
#define ID_SKIN_EXPORT                  32775
#define ID_FRAME_IMPORT                 32776
#define ID_FRAME_EXPORT                 32777
#define ID_ANIMATE_PLAY                 32778
#define ID_ANIMATE_STOP                 32779
#define ID_ANIMATE_STEP_FORE            32780
#define ID_BUTTON32781                  32781
#define ID_ANIMATE_TYPE_FRONT           32782
#define ID_ANIMATE_TYPE_BACK            32783
#define ID_ANIMATE_TYPE_PINGPONG        32784
#define ID_ANIMATE_STEP_BACK            32785
#define ID_LOCK_ROT_X                   32786
#define ID_LOCK_ROT_Y                   32787
#define ID_LOCK_ROT_Z                   32788
#define ID_LOCK_TRAN_X                  32789
#define ID_LOCK_TRAN_Y                  32790
#define ID_LOCK_TRAN_Z                  32791
#define ID_LOCK_SCALE_X                 32792
#define ID_LOCK_SCALE_Y                 32793
#define ID_LOCK_SCALE_Z                 32794
#define ID_ALL_UNLOCK                   32798
#define ID_ALL_LOCK                     32799
#define ID_RENDER_WIREFRAME             32800
#define ID_RENDER_FLAT                  32801
#define ID_RENDER_GOURAUD               32802
#define ID_RENDER_TEXTURE               32803
#define ID_RENDER_TRANS                 32804
#define ID_GOTOPOS_TOP                  32806
#define ID_GOTOPOS_BOTTOM               32807
#define ID_GOTOPOS_LEFT                 32808
#define ID_GOTOPOS_RIGHT                32809
#define ID_GOTOPOS_FRONT                32810
#define ID_GOTOPOS_BACK                 32811
#define ID_ANIMATE_INTER                32812
#define ID_ANIMATE_GOTOSTART            32826
#define ID_ANIMATE_GOTOEND              32827
#define ID_VIEW_ANIMBAR                 32828
#define ID_VIEW_POS                     32829
#define ID_PREF                         32831
#define ID_INDICATOR_FPS                32832
#define ID_ANIM_INTERTOGGLE             32833
#define ID_GOTOPOS_WEAPON               32835
#define ID_NODE_TOGGLE_VIS              32838
#define ID_NODE_PROP                    32840
#define ID_TIME_CLAMP                   32843
#define ID_TICKER_OPTIONS               32844
#define ID_TICK_TOGGLE                  32845
#define ID_SKIN_SHOWOVERLAY             32847
#define ID_WINDOW_SKIN                  32848
#define ID_WINDOW_FRAME                 32849
#define ID_MODE_CAMERA                  32851
#define ID_MODE_SKELETAL                32852
#define ID_SKELETON_SNAP                32853
#define ID_JOINT_MANUAL_ANGLES          32854
#define ID_JOINT_CONSTRAINTS            32855
#define ID_USE_JOINTS                   32856
#define ID_VIEW_PROPS                   32857
#define ID_USE_SKIN                     32858
#define ID_REPLACE_SKIN                 32859
#define IDR_QUAKE                       61216
#define IDR_QUAKE2                      61217
#define IDR_SKIN_FROM_FILE_START        62000
#define IDR_SKIN_FROM_FILE_END          62100
#define IDR_SKIN_SELECT_START           62101
#define ID_FILE_EXTENSIONS              62101
#define ID_SUPPORTED_FORMATS            62102
#define IDR_SKIN_SELECT_END             62200

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        177
#define _APS_NEXT_COMMAND_VALUE         32860
#define _APS_NEXT_CONTROL_VALUE         1025
#define _APS_NEXT_SYMED_VALUE           115
#endif
#endif
