/*
 * Copyright (C) 1997-2001 Id Software, Inc.
 * Copyright (C) 2011 Yamagi Burmeister
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or (at
 * your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * =======================================================================
 *
 * Prototypes for every function in the game.so.
 *
 * =======================================================================
 */

// die
extern void DBall_BallDie (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void actor_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void arachnid_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void army_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void barrel_delay (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void berserk_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void body_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void boss2_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void boss5_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void brain_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void button_killed (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void carrier_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void chick_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void commander_body_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void debris_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void demon_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void destructible_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void dog_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void door_killed (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void door_secret_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void doppleganger_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void enforcer_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void fd_secret_killed (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void fixbot_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void flipper_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void floater_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void flyer_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void func_explosive_explode (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void gekk_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void gib_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void gladb_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void gladiator_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void guardian_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void gunner_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void hknight_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void hover_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void infantry_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void insane_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void jorg_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void knight_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void makron_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void makron_torso_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void medic_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void misc_deadsoldier_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void monster_dynamic_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void monster_dynamic_die_noanim (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void mutant_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void nuke_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void ogre_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void parasite_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void player_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void prox_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void rotating_light_killed (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void rotfish_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void shalrath_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void shambler_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void soldier_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void soldierh_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void sphere_explode (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void sphere_if_idle_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void stalker_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void supertank_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void tank_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void tarbaby_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void tesla_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void turret_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void turret_driver_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void widow2_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void widow_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void wizard_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
extern void zombie_die (edict_t *, edict_t *, edict_t *, int, const vec3_t);
// pain
extern void DBall_BallPain (edict_t *, edict_t *, float, int);
extern void actor_pain (edict_t *, edict_t *, float, int);
extern void arachnid_pain (edict_t *, edict_t *, float, int);
extern void army_pain (edict_t *, edict_t *, float, int);
extern void berserk_pain (edict_t *, edict_t *, float, int);
extern void boss2_pain (edict_t *, edict_t *, float, int);
extern void boss5_pain (edict_t *, edict_t *, float, int);
extern void brain_pain (edict_t *, edict_t *, float, int);
extern void carrier_pain (edict_t *, edict_t *, float, int);
extern void chick_pain (edict_t *, edict_t *, float, int);
extern void defender_pain (edict_t *, edict_t *, float, int);
extern void demon_pain (edict_t *, edict_t *, float, int);
extern void dog_pain (edict_t *, edict_t *, float, int);
extern void doppleganger_pain (edict_t *, edict_t *, float, int);
extern void enforcer_pain (edict_t *, edict_t *, float, int);
extern void fixbot_pain (edict_t *, edict_t *, float, int);
extern void flipper_pain (edict_t *, edict_t *, float, int);
extern void floater_pain (edict_t *, edict_t *, float, int);
extern void flyer_pain (edict_t *, edict_t *, float, int);
extern void gekk_pain (edict_t *, edict_t *, float, int);
extern void gladb_pain (edict_t *, edict_t *, float, int);
extern void gladiator_pain (edict_t *, edict_t *, float, int);
extern void guardian_pain (edict_t *, edict_t *, float, int);
extern void gunner_pain (edict_t *, edict_t *, float, int);
extern void hknight_pain (edict_t *, edict_t *, float, int);
extern void hover_pain (edict_t *, edict_t *, float, int);
extern void hunter_pain (edict_t *, edict_t *, float, int);
extern void infantry_pain (edict_t *, edict_t *, float, int);
extern void insane_pain (edict_t *, edict_t *, float, int);
extern void jorg_pain (edict_t *, edict_t *, float, int);
extern void knight_pain (edict_t *, edict_t *, float, int);
extern void makron_pain (edict_t *, edict_t *, float, int);
extern void medic_pain (edict_t *, edict_t *, float, int);
extern void monster_dynamic_pain (edict_t *, edict_t *, float, int);
extern void monster_dynamic_pain_noanim (edict_t *, edict_t *, float, int);
extern void mutant_pain (edict_t *, edict_t *, float, int);
extern void ogre_pain (edict_t *, edict_t *, float, int);
extern void parasite_pain (edict_t *, edict_t *, float, int);
extern void player_pain (edict_t *, edict_t *, float, int);
extern void rotfish_pain (edict_t *, edict_t *, float, int);
extern void shalrath_pain (edict_t *, edict_t *, float, int);
extern void shambler_pain (edict_t *, edict_t *, float, int);
extern void soldier_pain (edict_t *, edict_t *, float, int);
extern void soldierh_pain (edict_t *, edict_t *, float, int);
extern void stalker_pain (edict_t *, edict_t *, float, int);
extern void supertank_pain (edict_t *, edict_t *, float, int);
extern void tank_pain (edict_t *, edict_t *, float, int);
extern void vengeance_pain (edict_t *, edict_t *, float, int);
extern void widow2_pain (edict_t *, edict_t *, float, int);
extern void widow_pain (edict_t *, edict_t *, float, int);
extern void wizard_pain (edict_t *, edict_t *, float, int);
extern void zombie_pain (edict_t *, edict_t *, float, int);
// prethink
extern void ChasecamTrack (edict_t *);
extern void misc_blackhole_transparent (edict_t *);
extern void misc_viper_bomb_prethink (edict_t *);
// think
extern void AI_Think (edict_t *);
extern void AngleMove_Begin (edict_t *);
extern void AngleMove_Done (edict_t *);
extern void AngleMove_Final (edict_t *);
extern void BOT_JoinBlue (edict_t *);
extern void BOT_JoinGame (edict_t *);
extern void BOT_JoinRed (edict_t *);
extern void BossExplode (edict_t *);
extern void BossExplode2 (edict_t *);
extern void CTFDropFlagThink (edict_t *);
extern void CTFFlagSetup (edict_t *);
extern void CTFFlagThink (edict_t *);
extern void ChasecamTrack (edict_t *);
extern void DBall_BallRespawn (edict_t *);
extern void DoRespawn (edict_t *);
extern void G_FreeEdict (edict_t *);
extern void Grenade_Explode (edict_t *);
extern void M_FliesOff (edict_t *);
extern void M_FliesOn (edict_t *);
extern void M_droptofloor (edict_t *);
extern void MakronSpawn (edict_t *);
extern void MegaHealth_think (edict_t *);
extern void Move_Begin (edict_t *);
extern void Move_Done (edict_t *);
extern void Move_Final (edict_t *);
extern void Nuke_Quake (edict_t *);
extern void Nuke_Think (edict_t *);
extern void Prox_Explode (edict_t *);
extern void SP_CreateCoopSpots (edict_t *);
extern void SP_CreateUnnamedSpawn (edict_t *);
extern void SP_FixCoopSpots (edict_t *);
extern void SpawnTechs (edict_t *);
extern void Tag_MakeTouchable (edict_t *);
extern void Tag_Respawn (edict_t *);
extern void Target_Help_Think (edict_t *);
extern void TechThink (edict_t *);
extern void Think_AccelMove (edict_t *);
extern void Think_Boss3Stand (edict_t *);
extern void Think_CalcMoveSpeed (edict_t *);
extern void Think_Delay (edict_t *);
extern void Think_SpawnDoorTrigger (edict_t *);
extern void Trap_Think (edict_t *);
extern void WidowExplode (edict_t *);
extern void amb4_think (edict_t *);
extern void barrel_explode (edict_t *);
extern void barrel_start (edict_t *);
extern void barrel_think (edict_t *);
extern void bfg_explode (edict_t *);
extern void bfg_think (edict_t *);
extern void blacklight_think (edict_t *);
extern void body_think (edict_t *);
extern void bot_goal_think (edict_t *);
extern void button_return (edict_t *);
extern void commander_body_drop (edict_t *);
extern void commander_body_think (edict_t *);
extern void dabeam_hit (edict_t *);
extern void defender_think (edict_t *);
extern void door_go_down (edict_t *);
extern void door_secret_move2 (edict_t *);
extern void door_secret_move4 (edict_t *);
extern void door_secret_move6 (edict_t *);
extern void doppleganger_timeout (edict_t *);
extern void drop_make_touchable (edict_t *);
extern void droptofloor (edict_t *);
extern void dynamicspawn_think (edict_t *);
extern void env_fire_think (edict_t *);
extern void fd_secret_move2 (edict_t *);
extern void fd_secret_move4 (edict_t *);
extern void fd_secret_move6 (edict_t *);
extern void fire_fly_think (edict_t *);
extern void flare_think (edict_t *);
extern void flymonster_start_go (edict_t *);
extern void force_wall_think (edict_t *);
extern void func_clock_think (edict_t *);
extern void func_object_release (edict_t *);
extern void func_timer_think (edict_t *);
extern void func_train_find (edict_t *);
extern void gib_think (edict_t *);
extern void heat_think (edict_t *);
extern void hover_deadthink (edict_t *);
extern void hunter_think (edict_t *);
extern void ionripper_sparks (edict_t *);
extern void makron_torso_think (edict_t *);
extern void mal_laser_think (edict_t *);
extern void misc_banner_think (edict_t *);
extern void misc_blackhole_think (edict_t *);
extern void misc_ctf_banner_think (edict_t *);
extern void misc_drip_think (edict_t *);
extern void misc_easterchick2_think (edict_t *);
extern void misc_easterchick_think (edict_t *);
extern void misc_eastertank_think (edict_t *);
extern void misc_hologram_infinity_destroy (edict_t *);
extern void misc_hologram_infinity_gib (edict_t *);
extern void misc_hologram_infinity_think (edict_t *);
extern void misc_hologram_think (edict_t *);
extern void misc_lightning_think (edict_t *);
extern void misc_player_mannequin_think (edict_t *);
extern void misc_rain_think (edict_t *);
extern void misc_satellite_dish_think (edict_t *);
extern void monster_think (edict_t *);
extern void monster_triggered_spawn (edict_t *);
extern void multi_wait (edict_t *);
extern void object_big_fire_think (edict_t *);
extern void object_repair_dead (edict_t *);
extern void object_repair_fx (edict_t *);
extern void object_repair_sparks (edict_t *);
extern void object_think (edict_t *);
extern void orb_think (edict_t *);
extern void plat2_go_down (edict_t *);
extern void plat2_go_up (edict_t *);
extern void plat_go_down (edict_t *);
extern void prox_open (edict_t *);
extern void prox_seek (edict_t *);
extern void rotating_accel (edict_t *);
extern void rotating_decel (edict_t *);
extern void rotating_light_alarm (edict_t *);
extern void shalrath_pod_home (edict_t *);
extern void smart_water_go_up (edict_t *);
extern void spawngrow_think (edict_t *);
extern void sphere_think_explode (edict_t *);
extern void stationarymonster_start_go (edict_t *);
extern void stationarymonster_triggered_spawn (edict_t *);
extern void swimmonster_start_go (edict_t *);
extern void tank_stand_think (edict_t *);
extern void tarbaby_explode (edict_t *);
extern void target_camera_dummy_think (edict_t *);
extern void target_crosslevel_target_think (edict_t *);
extern void target_crossunit_target_think (edict_t *);
extern void target_earthquake_think (edict_t *);
extern void target_explosion_explode (edict_t *);
extern void target_laser_start (edict_t *);
extern void target_laser_think (edict_t *);
extern void target_light_flicker_think (edict_t *);
extern void target_light_think (edict_t *);
extern void target_lightramp_think (edict_t *);
extern void target_steam_start (edict_t *);
extern void tesla_activate (edict_t *);
extern void tesla_think (edict_t *);
extern void tesla_think_active (edict_t *);
extern void tracker_fly (edict_t *);
extern void tracker_pain_daemon_think (edict_t *);
extern void train_next (edict_t *);
extern void trigger_elevator_init (edict_t *);
extern void trigger_push_active (edict_t *);
extern void trigger_push_inactive (edict_t *);
extern void turret_brain_link (edict_t *);
extern void turret_brain_think (edict_t *);
extern void turret_breach_finish_init (edict_t *);
extern void turret_breach_think (edict_t *);
extern void turret_driver_link (edict_t *);
extern void turret_driver_think (edict_t *);
extern void update_target_camera_think (edict_t *);
extern void update_target_soundfx (edict_t *);
extern void vengeance_think (edict_t *);
extern void viewthing_think (edict_t *);
extern void wait_and_change_think (edict_t *);
extern void walkmonster_start_go (edict_t *);
extern void widowlegs_think (edict_t *);
// touch
extern void CTFDropFlagTouch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void CTFGrappleTouch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void DBall_BallTouch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void DBall_GoalTouch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void DBall_SpeedTouch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void Grenade_Touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void Prox_Field_Touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void Touch_DoorTrigger (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void Touch_Item (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void Touch_Multi (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void Touch_Plat_Center (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void Touch_Plat_Center2 (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void badarea_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void barrel_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void bfg_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void blaster2_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void blaster_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void button_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void choose_cdtrack_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void demon_jump_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void dog_leap_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void door_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void drop_temp_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void dynamicspawn_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void enfbolt_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void fire_fly_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void flare_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void flechette_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void func_object_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void gekk_jump_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void gib_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void hint_path_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void hunter_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void hurt_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void ionripper_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void loogie_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void magic_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void misc_drip_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void misc_rain_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void misc_update_spawner_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void misc_viper_bomb_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void mutant_jump_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void nuke_bounce (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void path_corner_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void plasma_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void point_combat_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void prox_land (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void rocket_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void rotating_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void secret_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void shalrath_pod_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void spit_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void tarbaby_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void target_actor_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void teleporter_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void tesla_lava (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void tesla_zap (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void touch_npc_timeminder (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void tracker_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void trigger_disguise_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void trigger_flashlight_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void trigger_fog_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void trigger_fogdensity_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void trigger_gravity_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void trigger_mission_give_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void trigger_mission_take_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void trigger_monsterjump_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void trigger_push_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void trigger_teleport_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void vengeance_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void widow_gib_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void zombie_gib_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
extern void zombie_touch (edict_t *, edict_t *, const cplane_t *, const csurface_t *);
// use
extern void Door_Activate (edict_t *, edict_t *, edict_t *);
extern void Item_TriggeredSpawn (edict_t *, edict_t *, edict_t *);
extern void Use_Areaportal (edict_t *, edict_t *, edict_t *);
extern void Use_Boss3 (edict_t *, edict_t *, edict_t *);
extern void Use_Item (edict_t *, edict_t *, edict_t *);
extern void Use_Multi (edict_t *, edict_t *, edict_t *);
extern void Use_Plat (edict_t *, edict_t *, edict_t *);
extern void Use_Plat2 (edict_t *, edict_t *, edict_t *);
extern void Use_Target_Help (edict_t *, edict_t *, edict_t *);
extern void Use_Target_Speaker (edict_t *, edict_t *, edict_t *);
extern void Use_Target_Tent (edict_t *, edict_t *, edict_t *);
extern void actor_use (edict_t *, edict_t *, edict_t *);
extern void button_use (edict_t *, edict_t *, edict_t *);
extern void commander_body_use (edict_t *, edict_t *, edict_t *);
extern void door_secret_use (edict_t *, edict_t *, edict_t *);
extern void door_use (edict_t *, edict_t *, edict_t *);
extern void dynamic_light_use (edict_t *, edict_t *, edict_t *);
extern void fd_secret_use (edict_t *, edict_t *, edict_t *);
extern void force_wall_use (edict_t *, edict_t *, edict_t *);
extern void func_animation_use (edict_t *, edict_t *, edict_t *);
extern void func_clock_use (edict_t *, edict_t *, edict_t *);
extern void func_conveyor_use (edict_t *, edict_t *, edict_t *);
extern void func_explosive_activate (edict_t *, edict_t *, edict_t *);
extern void func_explosive_spawn (edict_t *, edict_t *, edict_t *);
extern void func_explosive_use (edict_t *, edict_t *, edict_t *);
extern void func_object_use (edict_t *, edict_t *, edict_t *);
extern void func_timer_use (edict_t *, edict_t *, edict_t *);
extern void func_wall_use (edict_t *, edict_t *, edict_t *);
extern void hurt_use (edict_t *, edict_t *, edict_t *);
extern void light_use (edict_t *, edict_t *, edict_t *);
extern void misc_blackhole_use (edict_t *, edict_t *, edict_t *);
extern void misc_flare_use (edict_t *, edict_t *, edict_t *);
extern void misc_hologram_infinity_use (edict_t *, edict_t *, edict_t *);
extern void misc_nuke_core_use (edict_t *, edict_t *, edict_t *);
extern void misc_player_mannequin_use (edict_t *, edict_t *, edict_t *);
extern void misc_satellite_dish_use (edict_t *, edict_t *, edict_t *);
extern void misc_strogg_ship_use (edict_t *, edict_t *, edict_t *);
extern void misc_text_caption_use (edict_t *, edict_t *, edict_t *);
extern void misc_viper_bomb_use (edict_t *, edict_t *, edict_t *);
extern void misc_viper_missile_use (edict_t *, edict_t *, edict_t *);
extern void misc_viper_use (edict_t *, edict_t *, edict_t *);
extern void monster_triggered_spawn_use (edict_t *, edict_t *, edict_t *);
extern void monster_use (edict_t *, edict_t *, edict_t *);
extern void plat2_activate (edict_t *, edict_t *, edict_t *);
extern void rotating_light_use (edict_t *, edict_t *, edict_t *);
extern void rotating_use (edict_t *, edict_t *, edict_t *);
extern void stationarymonster_triggered_spawn_use (edict_t *, edict_t *, edict_t *);
extern void target_anger_use (edict_t *, edict_t *, edict_t *);
extern void target_earthquake_use (edict_t *, edict_t *, edict_t *);
extern void target_killplayers_use (edict_t *, edict_t *, edict_t *);
extern void target_laser_use (edict_t *, edict_t *, edict_t *);
extern void target_light_use (edict_t *, edict_t *, edict_t *);
extern void target_lightramp_use (edict_t *, edict_t *, edict_t *);
extern void target_mal_laser_use (edict_t *, edict_t *, edict_t *);
extern void target_music_use (edict_t *, edict_t *, edict_t *);
extern void target_sky_use (edict_t *, edict_t *, edict_t *);
extern void target_string_use (edict_t *, edict_t *, edict_t *);
extern void train_use (edict_t *, edict_t *, edict_t *);
extern void trigger_counter_use (edict_t *, edict_t *, edict_t *);
extern void trigger_crosslevel_trigger_use (edict_t *, edict_t *, edict_t *);
extern void trigger_crossunit_trigger_use (edict_t *, edict_t *, edict_t *);
extern void trigger_disguise_use (edict_t *, edict_t *, edict_t *);
extern void trigger_elevator_use (edict_t *, edict_t *, edict_t *);
extern void trigger_enable (edict_t *, edict_t *, edict_t *);
extern void trigger_gravity_use (edict_t *, edict_t *, edict_t *);
extern void trigger_key_use (edict_t *, edict_t *, edict_t *);
extern void trigger_push_use (edict_t *, edict_t *, edict_t *);
extern void trigger_relay_use (edict_t *, edict_t *, edict_t *);
extern void trigger_teleport_use (edict_t *, edict_t *, edict_t *);
extern void turret_activate (edict_t *, edict_t *, edict_t *);
extern void turret_brain_activate (edict_t *, edict_t *, edict_t *);
extern void turret_brain_deactivate (edict_t *, edict_t *, edict_t *);
extern void use_killbox (edict_t *, edict_t *, edict_t *);
extern void use_nuke (edict_t *, edict_t *, edict_t *);
extern void use_target_autosave (edict_t *, edict_t *, edict_t *);
extern void use_target_blaster (edict_t *, edict_t *, edict_t *);
extern void use_target_camera (edict_t *, edict_t *, edict_t *);
extern void use_target_changelevel (edict_t *, edict_t *, edict_t *);
extern void use_target_explosion (edict_t *, edict_t *, edict_t *);
extern void use_target_goal (edict_t *, edict_t *, edict_t *);
extern void use_target_gravity (edict_t *, edict_t *, edict_t *);
extern void use_target_secret (edict_t *, edict_t *, edict_t *);
extern void use_target_soundfx (edict_t *, edict_t *, edict_t *);
extern void use_target_spawner (edict_t *, edict_t *, edict_t *);
extern void use_target_splash (edict_t *, edict_t *, edict_t *);
extern void use_target_steam (edict_t *, edict_t *, edict_t *);
extern void use_target_story (edict_t *, edict_t *, edict_t *);
// blocked
extern void door_blocked (edict_t *, edict_t *);
extern void door_secret_blocked (edict_t *, edict_t *);
extern void plat2_blocked (edict_t *, edict_t *);
extern void plat_blocked (edict_t *, edict_t *);
extern void rotating_blocked (edict_t *, edict_t *);
extern void secret_blocked (edict_t *, edict_t *);
extern void smart_water_blocked (edict_t *, edict_t *);
extern void train_blocked (edict_t *, edict_t *);
extern void turret_blocked (edict_t *, edict_t *);
// monsterinfo.stand
extern void actor_stand (edict_t *);
extern void berserk_stand (edict_t *);
extern void boss2_stand (edict_t *);
extern void boss5_stand (edict_t *);
extern void brain_stand (edict_t *);
extern void carrier_stand (edict_t *);
extern void chick_stand (edict_t *);
extern void fixbot_stand (edict_t *);
extern void flipper_stand (edict_t *);
extern void floater_stand (edict_t *);
extern void flyer_stand (edict_t *);
extern void gekk_stand (edict_t *);
extern void gladb_stand (edict_t *);
extern void gladiator_stand (edict_t *);
extern void guardian_stand (edict_t *);
extern void gunner_stand (edict_t *);
extern void hover_stand (edict_t *);
extern void infantry_stand (edict_t *);
extern void insane_stand (edict_t *);
extern void jorg_stand (edict_t *);
extern void makron_stand (edict_t *);
extern void medic_stand (edict_t *);
extern void monster_dynamic_stand (edict_t *);
extern void mutant_stand (edict_t *);
extern void ogre_stand (edict_t *);
extern void parasite_stand (edict_t *);
extern void shalrath_stand (edict_t *);
extern void shambler_stand (edict_t *);
extern void soldier_blind (edict_t *);
extern void soldier_stand (edict_t *);
extern void soldierh_stand (edict_t *);
extern void stalker_stand (edict_t *);
extern void supertank_stand (edict_t *);
extern void tank_stand (edict_t *);
extern void tarbaby_stand (edict_t *);
extern void turret_stand (edict_t *);
extern void widow2_stand (edict_t *);
extern void widow_stand (edict_t *);
// monsterinfo.walk
extern void actor_walk (edict_t *);
extern void arachnid_walk (edict_t *);
extern void army_run (edict_t *);
extern void berserk_walk (edict_t *);
extern void boss2_walk (edict_t *);
extern void boss5_walk (edict_t *);
extern void brain_walk (edict_t *);
extern void carrier_walk (edict_t *);
extern void chick_walk (edict_t *);
extern void demon_run (edict_t *);
extern void dog_run (edict_t *);
extern void fixbot_walk (edict_t *);
extern void flipper_walk (edict_t *);
extern void floater_walk (edict_t *);
extern void flyer_walk (edict_t *);
extern void gekk_walk (edict_t *);
extern void gladb_walk (edict_t *);
extern void gladiator_walk (edict_t *);
extern void guardian_walk (edict_t *);
extern void gunner_walk (edict_t *);
extern void hknight_run (edict_t *);
extern void hover_walk (edict_t *);
extern void infantry_walk (edict_t *);
extern void insane_walk (edict_t *);
extern void jorg_walk (edict_t *);
extern void knight_run (edict_t *);
extern void makron_walk (edict_t *);
extern void medic_walk (edict_t *);
extern void monster_dynamic_walk (edict_t *);
extern void mutant_walk (edict_t *);
extern void ogre_run (edict_t *);
extern void parasite_start_walk (edict_t *);
extern void shalrath_run (edict_t *);
extern void shambler_walk (edict_t *);
extern void soldier_walk (edict_t *);
extern void soldierh_walk (edict_t *);
extern void stalker_walk (edict_t *);
extern void supertank_walk (edict_t *);
extern void tank_walk (edict_t *);
extern void tarbaby_run (edict_t *);
extern void turret_walk (edict_t *);
extern void widow2_walk (edict_t *);
extern void widow_walk (edict_t *);
// monsterinfo.run
extern void actor_run (edict_t *);
extern void arachnid_run (edict_t *);
extern void army_run (edict_t *);
extern void berserk_run (edict_t *);
extern void boss2_run (edict_t *);
extern void boss5_run (edict_t *);
extern void brain_run (edict_t *);
extern void carrier_run (edict_t *);
extern void chick_run (edict_t *);
extern void demon_run (edict_t *);
extern void dog_run (edict_t *);
extern void enforcer_run (edict_t *);
extern void fixbot_run (edict_t *);
extern void flipper_start_run (edict_t *);
extern void floater_run (edict_t *);
extern void flyer_run (edict_t *);
extern void gekk_run_start (edict_t *);
extern void gladb_run (edict_t *);
extern void gladiator_run (edict_t *);
extern void guardian_run (edict_t *);
extern void gunner_run (edict_t *);
extern void hknight_run (edict_t *);
extern void hover_run (edict_t *);
extern void infantry_run (edict_t *);
extern void insane_run (edict_t *);
extern void jorg_run (edict_t *);
extern void knight_run (edict_t *);
extern void makron_run (edict_t *);
extern void medic_run (edict_t *);
extern void monster_dynamic_run (edict_t *);
extern void mutant_run (edict_t *);
extern void ogre_run (edict_t *);
extern void parasite_start_run (edict_t *);
extern void shalrath_run (edict_t *);
extern void shambler_run (edict_t *);
extern void soldier_run (edict_t *);
extern void soldierh_run (edict_t *);
extern void stalker_run (edict_t *);
extern void supertank_run (edict_t *);
extern void tank_run (edict_t *);
extern void tarbaby_run (edict_t *);
extern void turret_run (edict_t *);
extern void widow2_run (edict_t *);
extern void widow_run (edict_t *);
extern void zombie_run (edict_t *);
// monsterinfo.melee
extern void berserk_melee (edict_t *);
extern void brain_melee (edict_t *);
extern void chick_melee (edict_t *);
extern void demon_melee (edict_t *);
extern void dog_melee (edict_t *);
extern void flipper_melee (edict_t *);
extern void floater_melee (edict_t *);
extern void flyer_melee (edict_t *);
extern void gekk_melee (edict_t *);
extern void gladb_melee (edict_t *);
extern void gladiator_melee (edict_t *);
extern void hknight_melee (edict_t *);
extern void knight_melee (edict_t *);
extern void monster_dynamic_melee (edict_t *);
extern void mutant_melee (edict_t *);
extern void ogre_melee (edict_t *);
extern void rotfish_melee (edict_t *);
extern void shambler_melee (edict_t *);
extern void stalker_attack_melee (edict_t *);
extern void widow2_melee (edict_t *);
extern void widow_melee (edict_t *);
// monsterinfo.attack
extern void actor_attack (edict_t *);
extern void arachnid_attack (edict_t *);
extern void army_attack (edict_t *);
extern void boss2_attack (edict_t *);
extern void boss5_attack (edict_t *);
extern void brain_attack (edict_t *);
extern void carrier_attack (edict_t *);
extern void chick_attack (edict_t *);
extern void demon_attack (edict_t *);
extern void dog_leap (edict_t *);
extern void enforcer_attack (edict_t *);
extern void fixbot_attack (edict_t *);
extern void floater_attack (edict_t *);
extern void flyer_attack (edict_t *);
extern void gekk_jump (edict_t *);
extern void gladb_attack (edict_t *);
extern void gladiator_attack (edict_t *);
extern void guardian_attack (edict_t *);
extern void gunner_attack (edict_t *);
extern void hknight_attack (edict_t *);
extern void hover_start_attack (edict_t *);
extern void infantry_attack (edict_t *);
extern void jorg_attack (edict_t *);
extern void knight_attack (edict_t *);
extern void makron_attack (edict_t *);
extern void medic_attack (edict_t *);
extern void monster_dynamic_attack (edict_t *);
extern void mutant_jump (edict_t *);
extern void ogre_attack (edict_t *);
extern void parasite_attack (edict_t *);
extern void shalrath_attack (edict_t *);
extern void shambler_attack (edict_t *);
extern void soldier_attack (edict_t *);
extern void soldierh_attack (edict_t *);
extern void stalker_attack_ranged (edict_t *);
extern void supertank_attack (edict_t *);
extern void tank_attack (edict_t *);
extern void tarbaby_attack (edict_t *);
extern void turret_attack (edict_t *);
extern void widow2_attack (edict_t *);
extern void widow_attack (edict_t *);
extern void wizard_attack (edict_t *);
extern void zombie_attack (edict_t *);
// monsterinfo.checkattack
extern qboolean Boss2_CheckAttack (edict_t *);
extern qboolean Carrier_CheckAttack (edict_t *);
extern qboolean Jorg_CheckAttack (edict_t *);
extern qboolean M_CheckAttack (edict_t *);
extern qboolean Makron_CheckAttack (edict_t *);
extern qboolean Widow2_CheckAttack (edict_t *);
extern qboolean Widow_CheckAttack (edict_t *);
extern qboolean gekk_checkattack (edict_t *);
extern qboolean medic_checkattack (edict_t *);
extern qboolean mutant_checkattack (edict_t *);
extern qboolean parasite_checkattack (edict_t *);
extern qboolean turret_checkattack (edict_t *);
// monsterinfo.dodge
extern void M_MonsterDodge (edict_t *, edict_t *, float, trace_t *trace);
extern void brain_dodge (edict_t *, edict_t *, float, trace_t *trace);
extern void chick_dodge (edict_t *, edict_t *, float, trace_t *trace);
extern void gekk_dodge (edict_t *, edict_t *, float, trace_t *trace);
extern void gunner_dodge (edict_t *, edict_t *, float, trace_t *trace);
extern void infantry_dodge (edict_t *, edict_t *, float, trace_t *trace);
extern void medic_dodge (edict_t *, edict_t *, float, trace_t *trace);
extern void monster_dynamic_dodge (edict_t *, edict_t *, float, trace_t *trace);
extern void soldier_dodge (edict_t *, edict_t *, float, trace_t *trace);
extern void soldierh_dodge (edict_t *, edict_t *, float, trace_t *trace);
extern void stalker_dodge (edict_t *, edict_t *, float, trace_t *trace);
// monsterinfo.idle
extern void brain_idle (edict_t *);
extern void flipper_idle (edict_t *);
extern void floater_idle (edict_t *);
extern void flyer_idle (edict_t *);
extern void gekk_idle (edict_t *);
extern void gladb_idle (edict_t *);
extern void gladiator_idle (edict_t *);
extern void infantry_fidget (edict_t *);
extern void medic_idle (edict_t *);
extern void monster_dynamic_idle (edict_t *);
extern void mutant_idle (edict_t *);
extern void parasite_idle (edict_t *);
extern void shambler_idle (edict_t *);
extern void stalker_idle (edict_t *);
extern void tank_idle (edict_t *);
// monsterinfo.search
extern void army_search (edict_t *);
extern void berserk_search (edict_t *);
extern void boss2_search (edict_t *);
extern void boss5_search (edict_t *);
extern void brain_search (edict_t *);
extern void chick_search (edict_t *);
extern void demon_search (edict_t *);
extern void dog_search (edict_t *);
extern void enforcer_search (edict_t *);
extern void flipper_search (edict_t *);
extern void gekk_search (edict_t *);
extern void gladb_search (edict_t *);
extern void gladiator_search (edict_t *);
extern void gunner_search (edict_t *);
extern void hknight_search (edict_t *);
extern void hover_search (edict_t *);
extern void infantry_search (edict_t *);
extern void jorg_search (edict_t *);
extern void knight_search (edict_t *);
extern void medic_search (edict_t *);
extern void monster_dynamic_search (edict_t *);
extern void mutant_search (edict_t *);
extern void ogre_search (edict_t *);
extern void parasite_search (edict_t *);
extern void rotfish_search (edict_t *);
extern void shalrath_search (edict_t *);
extern void supertank_search (edict_t *);
extern void widow2_search (edict_t *);
extern void wizard_search (edict_t *);
extern void zombie_search (edict_t *);
// monsterinfo.sight
extern void arachnid_sight (edict_t *, edict_t *);
extern void army_sight (edict_t *, edict_t *);
extern void berserk_sight (edict_t *, edict_t *);
extern void brain_sight (edict_t *, edict_t *);
extern void carrier_sight (edict_t *, edict_t *);
extern void chick_sight (edict_t *, edict_t *);
extern void demon_sight (edict_t *, edict_t *);
extern void dog_sight (edict_t *, edict_t *);
extern void enforcer_sight (edict_t *, edict_t *);
extern void flipper_sight (edict_t *, edict_t *);
extern void floater_sight (edict_t *, edict_t *);
extern void flyer_sight (edict_t *, edict_t *);
extern void gekk_sight (edict_t *, edict_t *);
extern void gladb_sight (edict_t *, edict_t *);
extern void gladiator_sight (edict_t *, edict_t *);
extern void gunner_sight (edict_t *, edict_t *);
extern void hknight_sight (edict_t *, edict_t *);
extern void hover_sight (edict_t *, edict_t *);
extern void infantry_sight (edict_t *, edict_t *);
extern void knight_sight (edict_t *, edict_t *);
extern void medic_sight (edict_t *, edict_t *);
extern void monster_dynamic_sight (edict_t *, edict_t *);
extern void mutant_sight (edict_t *, edict_t *);
extern void ogre_sight (edict_t *, edict_t *);
extern void parasite_sight (edict_t *, edict_t *);
extern void shalrath_sight (edict_t *, edict_t *);
extern void shambler_sight (edict_t *, edict_t *);
extern void soldier_sight (edict_t *, edict_t *);
extern void soldierh_sight (edict_t *, edict_t *);
extern void stalker_sight (edict_t *, edict_t *);
extern void tank_sight (edict_t *, edict_t *);
extern void tarbaby_sight (edict_t *, edict_t *);
extern void widow_sight (edict_t *, edict_t *);
extern void wizard_sight (edict_t *, edict_t *);
extern void zombie_sight (edict_t *, edict_t *);
// monsterinfo.blocked
extern qboolean berserk_blocked (edict_t *self, float dist);
extern qboolean chick_blocked (edict_t *self, float dist);
extern qboolean gladiator_blocked (edict_t *self, float dist);
extern qboolean gunner_blocked (edict_t *self, float dist);
extern qboolean hover_blocked (edict_t *self, float dist);
extern qboolean infantry_blocked (edict_t *self, float dist);
extern qboolean medic_blocked (edict_t *self, float dist);
extern qboolean mutant_blocked (edict_t *self, float dist);
extern qboolean parasite_blocked (edict_t *self, float dist);
extern qboolean soldier_blocked (edict_t *self, float dist);
extern qboolean stalker_blocked (edict_t *self, float dist);
extern qboolean supertank_blocked (edict_t *self, float dist);
extern qboolean tank_blocked (edict_t *self, float dist);
extern qboolean widow_blocked (edict_t *self, float dist);
// monsterinfo.duck
extern void brain_duck (edict_t *self, float eta);
extern void chick_duck (edict_t *self, float eta);
extern void gunner_duck (edict_t *self, float eta);
extern void infantry_duck (edict_t *self, float eta);
extern void medic_duck (edict_t *self, float eta);
extern void soldier_duck (edict_t *self, float eta);
// monsterinfo.unduck
extern void monster_duck_up (edict_t *self);
// monsterinfo.sidestep
extern void berserk_sidestep (edict_t *self);
extern void chick_sidestep (edict_t *self);
extern void gunner_sidestep (edict_t *self);
extern void infantry_sidestep (edict_t *self);
extern void medic_sidestep (edict_t *self);
extern void soldier_sidestep (edict_t *self);
// moveinfo.endfunc
extern void button_done (edict_t *);
extern void button_wait (edict_t *);
extern void door_hit_bottom (edict_t *);
extern void door_hit_top (edict_t *);
extern void door_secret_done (edict_t *);
extern void door_secret_move1 (edict_t *);
extern void door_secret_move3 (edict_t *);
extern void door_secret_move5 (edict_t *);
extern void plat_hit_bottom (edict_t *);
extern void plat_hit_top (edict_t *);
extern void train_wait (edict_t *);
